version: 0.2
phases:
  install:
    commands:
      - echo "Install Phase - Nothing to do"
  pre_build:
    commands:
      # Docker Image Tag with Date Time & Code Buiild Resolved Source Version
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      # Verify AWS CLI Version
      - echo $TAG
      - echo "Verify AWS CLI Version..."
      - aws --version
      # Login to ECR Registry for docker to push the image to ECR Repository
      - echo "Login in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email)
      # Update Kube config Home Directory
      - export KUBECONFIG=$HOME/.kube/config
      - cd test-image
      - mvn clean install
      - EKS_CLUSTER_NAME=tingo-dev-cluster
      - REPOSITORY_URI=096527414900.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo
  build:
    commands:
      # Build Docker Imaget
      - now=$(date)
      - echo "Build started on $now"
      - echo "Building the Docker image..."
      - docker build --tag $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$TAG .
  post_build:
    commands:
      # Push Docker Image to ECR Repository
      - echo "Build completed on $now"
      - echo "Pushing the Docker image to ECR Repository"
      - docker push $REPOSITORY_URI:$TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Docker Image Push to ECR Completed -  $REPOSITORY_URI:$TAG"
